gpu_fdinfo: add missing implicit sstream header include
It's not implicit in gcc-16 anymore.

../src/gpu_fdinfo.cpp: In member function ‘void GPU_fdinfo::get_current_hwmon_readings()’:
../src/gpu_fdinfo.cpp:287:27: error: aggregate ‘std::stringstream ss’ has incomplete type and cannot be defined
  287 |         std::stringstream ss;
      |

Signed-off-by: Alfred Wingate <parona@protonmail.com>